# Generated by Django 5.0 on 2025-07-31 17:24

import django.db.models.deletion
import django_tenants.postgresql_backend.base
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(db_index=True, max_length=63, unique=True, validators=[django_tenants.postgresql_backend.base._check_schema_name])),
                ('name', models.CharField(max_length=100)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('max_users', models.IntegerField(default=100)),
                ('features_enabled', models.JSONField(default=dict)),
                ('billing_settings', models.JSONField(default=dict)),
                ('ai_config_encrypted', models.TextField(blank=True, help_text='Encrypted AI configuration including API keys', null=True)),
                ('ai_enabled', models.BooleanField(default=False, help_text='Enable AI features for this tenant')),
                ('ai_usage_limit', models.DecimalField(decimal_places=2, default=100.0, help_text='Monthly AI usage limit in USD', max_digits=10)),
                ('ai_current_usage', models.DecimalField(decimal_places=2, default=0.0, help_text='Current month AI usage in USD', max_digits=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=253, unique=True)),
                ('is_primary', models.BooleanField(db_index=True, default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='tenants.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
