# Generated by Django 5.0 on 2025-08-06 20:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, help_text='Whether maintenance mode is currently active')),
                ('reason', models.CharField(help_text="Reason for maintenance (e.g., 'Schema Migration', 'System Update')", max_length=200)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When maintenance mode was activated')),
                ('estimated_completion', models.DateTimeField(blank=True, help_text='Estimated completion time', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When maintenance mode was deactivated', null=True)),
                ('progress_percentage', models.IntegerField(default=0, help_text='Progress percentage (0-100)')),
                ('status_message', models.TextField(blank=True, help_text='Current status message to display to users')),
                ('migration_type', models.CharField(blank=True, help_text='Type of migration being performed (field_rename, type_change, etc.)', max_length=100)),
                ('migration_data', models.JSONField(default=dict, help_text='Migration-specific data and parameters')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who initiated maintenance mode', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.OneToOneField(help_text='Tenant under maintenance', on_delete=django.db.models.deletion.CASCADE, related_name='maintenance', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['is_active'], name='tenants_ten_is_acti_5d20da_idx'), models.Index(fields=['started_at'], name='tenants_ten_started_b331f4_idx')],
            },
        ),
    ]
