# Generated by Django 5.0 on 2025-09-03 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_tenantmaintenance'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='branding_settings',
            field=models.JSONField(default=dict, help_text='Contains: primary_color, secondary_color, email_header_html, login_message'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='business_hours',
            field=models.JSONField(default=dict, help_text='Business hours by day of week'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='data_policies',
            field=models.JSONField(default=dict, help_text='Contains: retention_days, backup_frequency, auto_archive_days, export_formats'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='localization_settings',
            field=models.JSONField(default=dict, help_text='Contains: timezone, date_format, time_format, currency, language, week_start_day'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='organization_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='organization_logo',
            field=models.ImageField(blank=True, null=True, upload_to='tenant_logos/'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='security_policies',
            field=models.JSONField(default=dict, help_text='Contains: password_min_length, password_complexity, session_timeout_minutes, require_2fa, ip_whitelist'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='support_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='tenant',
            name='support_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
