# Generated by Django 5.0 on 2025-09-04 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_add_tenant_settings_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='branding_settings',
            field=models.JSONField(default=dict, help_text='Contains: primary_color, secondary_color, email_header_html, login_message, email_signature_template, email_signature_enabled'),
        ),
    ]
