# Generated by Django 5.0 on 2025-09-04 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_add_email_signature_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='organization_website',
            field=models.URLField(blank=True, help_text='Organization website URL (e.g., https://example.com)', max_length=500),
        ),
    ]
