# Generated by Django 5.0 on 2025-09-03 12:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(help_text='Unique employee identifier', max_length=50, unique=True)),
                ('job_title', models.CharField(max_length=255)),
                ('department', models.CharField(blank=True, max_length=255)),
                ('employment_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contractor', 'Contractor'), ('intern', 'Intern'), ('consultant', 'Consultant')], default='full_time', max_length=20)),
                ('employment_status', models.CharField(choices=[('active', 'Active'), ('on_leave', 'On Leave'), ('terminated', 'Terminated'), ('resigned', 'Resigned')], default='active', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('work_location', models.CharField(choices=[('office', 'Office'), ('remote', 'Remote'), ('hybrid', 'Hybrid')], default='office', max_length=20)),
                ('office_location', models.CharField(blank=True, max_length=255)),
                ('work_phone_extension', models.CharField(blank=True, max_length=20)),
                ('certifications', models.JSONField(default=list, help_text='Array of professional certifications')),
                ('languages_spoken', models.JSONField(default=list, help_text='Array of languages spoken')),
                ('education', models.JSONField(default=dict, help_text='Education details including degrees, institutions, and years')),
                ('bio', models.TextField(blank=True, help_text='Professional biography or summary')),
                ('linkedin_profile', models.URLField(blank=True, help_text='LinkedIn profile URL', max_length=500)),
                ('professional_links', models.JSONField(default=dict, help_text='Other professional profile links (GitHub, portfolio, etc.)')),
                ('emergency_contact_name', models.CharField(blank=True, max_length=255)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=50)),
                ('emergency_contact_relationship', models.CharField(blank=True, max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, max_length=100)),
                ('personal_email', models.EmailField(blank=True, max_length=254)),
                ('home_address', models.JSONField(default=dict, help_text='Home address details')),
                ('internal_notes', models.TextField(blank=True, help_text='Internal HR notes (permission-restricted)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_staff_profiles', to=settings.AUTH_USER_MODEL)),
                ('reporting_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_reports', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'auth_staffprofile',
                'ordering': ['employee_id'],
                'indexes': [models.Index(fields=['employee_id'], name='auth_staffp_employe_b2cdaa_idx'), models.Index(fields=['department'], name='auth_staffp_departm_a8471e_idx'), models.Index(fields=['reporting_manager'], name='auth_staffp_reporti_e8bc26_idx'), models.Index(fields=['employment_status'], name='auth_staffp_employm_79ef13_idx')],
            },
        ),
    ]
