# Generated by Django 5.0 on 2025-09-03 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_staffprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffprofile',
            name='languages_spoken',
        ),
    ]
