# Generated by Django 5.0 on 2025-09-04 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_remove_languages_spoken_from_staffprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='employee_id',
            field=models.CharField(blank=True, help_text='Unique employee identifier', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='employment_status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('on_leave', 'On Leave'), ('terminated', 'Terminated'), ('resigned', 'Resigned')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='employment_type',
            field=models.CharField(blank=True, choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contractor', 'Contractor'), ('intern', 'Intern'), ('consultant', 'Consultant')], default='full_time', max_length=20),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='job_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='work_location',
            field=models.CharField(blank=True, choices=[('office', 'Office'), ('remote', 'Remote'), ('hybrid', 'Hybrid')], default='office', max_length=20),
        ),
    ]
