# Generated by Django 5.0 on 2025-09-04 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_make_staff_profile_fields_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='emergency_contact_relationship',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='internal_notes',
            field=models.TextField(blank=True, help_text='Internal HR notes (permission-restricted)', null=True),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='linkedin_profile',
            field=models.URLField(blank=True, help_text='LinkedIn profile URL', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='nationality',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='personal_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
