# Generated by Django 5.0 on 2025-07-29 07:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0001_initial'),
        ('relationships', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='relationshiptype',
            name='allow_user_relationships',
            field=models.BooleanField(default=False, help_text='Allow this relationship type to be used for user-to-record assignments'),
        ),
        migrations.CreateModel(
            name='UserRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_record_id', models.IntegerField()),
                ('role', models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('viewer', 'Viewer'), ('collaborator', 'Collaborator')], default='primary', max_length=50)),
                ('metadata', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending')], default='active', max_length=50)),
                ('can_edit', models.BooleanField(default=True)),
                ('can_delete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_user_relationships', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_user_relationships', to=settings.AUTH_USER_MODEL)),
                ('relationship_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relationships.relationshiptype')),
                ('target_pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_relationships', to='pipelines.pipeline')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record_relationships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'relationships_userrelationship',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='relationshi_user_id_1c957c_idx'), models.Index(fields=['target_pipeline', 'target_record_id'], name='relationshi_target__b82750_idx'), models.Index(fields=['relationship_type'], name='relationshi_relatio_37e42e_idx'), models.Index(fields=['status'], name='relationshi_status_c74f81_idx'), models.Index(fields=['is_deleted'], name='relationshi_is_dele_2b1ee1_idx'), models.Index(condition=models.Q(('is_deleted', False)), fields=['user', 'relationship_type'], name='idx_user_rel_type_active'), models.Index(condition=models.Q(('is_deleted', False)), fields=['target_pipeline', 'target_record_id', 'relationship_type'], name='idx_target_rel_type_active')],
                'unique_together': {('relationship_type', 'user', 'target_pipeline', 'target_record_id')},
            },
        ),
    ]
