# Generated by Django 5.0 on 2025-07-29 07:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0001_initial'),
        ('relationships', '0002_relationshiptype_allow_user_relationships_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userrelationship',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='userrelationship',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='userrelationship',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='userrelationship',
            name='relationship_type',
        ),
        migrations.RemoveField(
            model_name='userrelationship',
            name='target_pipeline',
        ),
        migrations.RemoveField(
            model_name='userrelationship',
            name='user',
        ),
        migrations.RemoveIndex(
            model_name='relationship',
            name='idx_rel_src_type_active',
        ),
        migrations.RemoveIndex(
            model_name='relationship',
            name='idx_rel_tgt_type_active',
        ),
        migrations.AlterUniqueTogether(
            name='relationship',
            unique_together={('relationship_type', 'source_pipeline', 'source_record_id', 'target_pipeline', 'target_record_id')},
        ),
        migrations.AddField(
            model_name='relationship',
            name='can_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='relationship',
            name='can_edit',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='relationship',
            name='role',
            field=models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('viewer', 'Viewer'), ('collaborator', 'Collaborator')], default='primary', help_text='Role of the user in this relationship (for user-to-record relationships)', max_length=50),
        ),
        migrations.AddField(
            model_name='relationship',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User involved in this relationship (for user-to-record relationships)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relationships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='source_pipeline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relationships', to='pipelines.pipeline'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='source_record_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='relationship',
            unique_together={('relationship_type', 'source_pipeline', 'source_record_id', 'target_pipeline', 'target_record_id'), ('relationship_type', 'user', 'target_pipeline', 'target_record_id', 'role')},
        ),
        migrations.AddIndex(
            model_name='relationship',
            index=models.Index(fields=['user'], name='relationshi_user_id_cce9c2_idx'),
        ),
        migrations.AddIndex(
            model_name='relationship',
            index=models.Index(fields=['role'], name='relationshi_role_80aa3e_idx'),
        ),
        migrations.AddIndex(
            model_name='relationship',
            index=models.Index(fields=['created_at'], name='relationshi_created_184787_idx'),
        ),
        migrations.AddIndex(
            model_name='relationship',
            index=models.Index(condition=models.Q(('is_deleted', False), ('user__isnull', True)), fields=['source_pipeline', 'source_record_id', 'relationship_type'], name='idx_rel_src_type_active'),
        ),
        migrations.AddIndex(
            model_name='relationship',
            index=models.Index(condition=models.Q(('is_deleted', False), ('user__isnull', True)), fields=['target_pipeline', 'target_record_id', 'relationship_type'], name='idx_rel_tgt_type_active'),
        ),
        migrations.AddIndex(
            model_name='relationship',
            index=models.Index(condition=models.Q(('is_deleted', False), ('user__isnull', False)), fields=['user', 'relationship_type', 'status'], name='idx_user_rel_status_active'),
        ),
        migrations.AddIndex(
            model_name='relationship',
            index=models.Index(condition=models.Q(('is_deleted', False), ('user__isnull', False)), fields=['target_pipeline', 'target_record_id', 'user'], name='idx_target_user_active'),
        ),
        migrations.AddIndex(
            model_name='relationship',
            index=models.Index(condition=models.Q(('is_deleted', False), ('user__isnull', False)), fields=['user', 'role'], name='idx_user_role_active'),
        ),
        migrations.AddIndex(
            model_name='relationship',
            index=models.Index(condition=models.Q(('is_deleted', False)), fields=['relationship_type', 'status'], name='idx_type_status_active'),
        ),
        migrations.AddConstraint(
            model_name='relationship',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('source_pipeline__isnull', True), ('source_record_id__isnull', True), ('user__isnull', False)), models.Q(('source_pipeline__isnull', False), ('source_record_id__isnull', False), ('user__isnull', True)), _connector='OR'), name='relationship_source_constraint'),
        ),
        migrations.DeleteModel(
            name='UserRelationship',
        ),
    ]
