# Generated by Django 5.0 on 2025-08-16 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenantunipileconfig',
            name='access_token_encrypted',
        ),
        migrations.RemoveField(
            model_name='tenantunipileconfig',
            name='dsn',
        ),
        migrations.AddField(
            model_name='userchannelconnection',
            name='account_status',
            field=models.CharField(choices=[('pending', 'Pending Connection'), ('active', 'Active'), ('failed', 'Failed'), ('expired', 'Expired'), ('checkpoint_required', 'Checkpoint Required'), ('disconnected', 'Disconnected')], default='pending', help_text='Current account status', max_length=50),
        ),
        migrations.AddField(
            model_name='userchannelconnection',
            name='checkpoint_data',
            field=models.JSONField(default=dict, help_text='2FA/checkpoint data for authentication challenges'),
        ),
        migrations.AddField(
            model_name='userchannelconnection',
            name='hosted_auth_url',
            field=models.URLField(blank=True, help_text='Hosted authentication URL for pending connections'),
        ),
        migrations.AddField(
            model_name='userchannelconnection',
            name='last_rate_limit_reset',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userchannelconnection',
            name='messages_sent_today',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userchannelconnection',
            name='rate_limit_per_hour',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='tenantunipileconfig',
            name='webhook_secret',
            field=models.CharField(blank=True, help_text='Optional tenant-specific webhook secret', max_length=255),
        ),
    ]
