# Generated by Django 5.0 on 2025-08-16 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0005_add_draft_models'),
    ]

    operations = [
    ]
