# Generated by Django 5.0 on 2025-08-16 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0008_final_state_alignment'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='messagedraft',
            new_name='communicati_user_id_92b37b_idx',
            old_name='communicati_user_id_ca9b3b_idx',
        ),
        migrations.RenameIndex(
            model_name='messagedraft',
            new_name='communicati_user_id_218340_idx',
            old_name='communicati_user_id_e4a0f1_idx',
        ),
        migrations.RenameIndex(
            model_name='messagedraft',
            new_name='communicati_user_id_61ab77_idx',
            old_name='communicati_user_id_b9e4c1_idx',
        ),
        migrations.RenameIndex(
            model_name='messagedraft',
            new_name='communicati_last_au_347c84_idx',
            old_name='communicati_last_au_d2e45a_idx',
        ),
        migrations.AlterField(
            model_name='userchannelconnection',
            name='messages_sent_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userchannelconnection',
            name='provider_config',
            field=models.JSONField(default=dict, help_text='Provider-specific configuration and preferences'),
        ),
        migrations.AlterField(
            model_name='userchannelconnection',
            name='unipile_account_id',
            field=models.CharField(blank=True, default='', help_text='UniPile account ID', max_length=255),
        ),
    ]
