# Generated by Django 5.0 on 2025-08-18 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0009_rename_communicati_user_id_ca9b3b_idx_communicati_user_id_92b37b_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='contact_phone',
            field=models.CharField(blank=True, help_text='Contact phone number for WhatsApp/SMS messages', max_length=50),
        ),
    ]
