# Generated by Django 5.0 on 2025-08-18 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0010_add_contact_phone_to_message'),
        ('pipelines', '0016_update_pipeline_types'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='message',
            constraint=models.UniqueConstraint(condition=models.Q(('external_message_id__isnull', False), models.Q(('external_message_id', ''), _negated=True)), fields=('external_message_id', 'channel'), name='unique_external_message_per_channel'),
        ),
    ]
