# Generated by Django 5.0 on 2025-08-19 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0011_add_message_external_id_unique_constraint'),
        ('pipelines', '0016_update_pipeline_types'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='conversation',
            name='communicati_channel_6884b9_idx',
        ),
        migrations.RemoveIndex(
            model_name='conversation',
            name='communicati_last_me_5926ff_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='communicati_channel_0ffaee_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='communicati_convers_b5d10e_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='communicati_contact_988a44_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='communicati_sent_at_91b226_idx',
        ),
        migrations.AddField(
            model_name='conversation',
            name='is_hot',
            field=models.BooleanField(default=False, help_text='Frequently accessed conversation'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='last_accessed_at',
            field=models.DateTimeField(auto_now=True, help_text='Last time conversation was accessed'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, help_text='Last successful sync timestamp', null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='sync_error_count',
            field=models.IntegerField(default=0, help_text='Number of consecutive sync failures'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='sync_error_message',
            field=models.TextField(blank=True, help_text='Last sync error message'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='sync_status',
            field=models.CharField(choices=[('pending', 'Pending Sync'), ('synced', 'Synced'), ('failed', 'Sync Failed'), ('partial', 'Partially Synced')], default='pending', help_text='Synchronization status with external provider', max_length=20),
        ),
        migrations.AddField(
            model_name='conversation',
            name='unread_count',
            field=models.IntegerField(default=0, help_text='Cached unread message count'),
        ),
        migrations.AddField(
            model_name='message',
            name='is_local_only',
            field=models.BooleanField(default=False, help_text='Message exists only locally (not yet sent to external provider)'),
        ),
        migrations.AddField(
            model_name='message',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, help_text='Last successful sync timestamp', null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='sync_status',
            field=models.CharField(choices=[('pending', 'Pending Sync'), ('synced', 'Synced'), ('failed', 'Sync Failed')], default='pending', help_text='Synchronization status with external provider', max_length=20),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['channel', 'status', '-last_message_at'], name='communicati_channel_110fe7_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['channel', '-last_message_at'], name='communicati_channel_76d555_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['sync_status', 'last_synced_at'], name='communicati_sync_st_8e265b_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['is_hot', '-last_accessed_at'], name='communicati_is_hot_e976c3_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['-last_accessed_at'], name='communicati_last_ac_d00d65_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['status', '-last_message_at'], name='communicati_status_2b15a1_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['unread_count'], name='communicati_unread__8dcc9c_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['-created_at'], name='communicati_created_1842c1_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['-updated_at'], name='communicati_updated_08da92_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', '-created_at'], name='communicati_convers_973c5c_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['channel', 'direction', '-created_at'], name='communicati_channel_18a3d1_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sync_status', 'last_synced_at'], name='communicati_sync_st_603950_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['is_local_only', '-created_at'], name='communicati_is_loca_6c79f3_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['contact_record', '-created_at'], name='communicati_contact_ccf76b_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['contact_phone'], name='communicati_contact_91fcca_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['-sent_at'], name='communicati_sent_at_4f86f6_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['-received_at'], name='communicati_receive_8837ac_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['-created_at'], name='communicati_created_2d065c_idx'),
        ),
    ]
