# Generated by Django 5.0 on 2025-08-20 13:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0012_add_persistence_layer_fields'),
        ('pipelines', '0016_update_pipeline_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatAttendee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_attendee_id', models.CharField(help_text='Unipile attendee ID', max_length=255)),
                ('provider_id', models.CharField(help_text='Provider-specific ID (e.g., phone@s.whatsapp.net, email, etc.)', max_length=255)),
                ('name', models.CharField(help_text='Display name of the attendee', max_length=255)),
                ('picture_url', models.URLField(blank=True, help_text='Profile picture URL from the platform')),
                ('is_self', models.BooleanField(default=False, help_text='Whether this attendee represents the account owner')),
                ('metadata', models.JSONField(default=dict, help_text='Additional attendee data from Unipile API')),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
                ('sync_status', models.CharField(choices=[('active', 'Active'), ('stale', 'Stale'), ('error', 'Error')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(help_text='Channel this attendee belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='communications.channel')),
                ('contact_record', models.ForeignKey(blank=True, help_text='Linked contact record in CRM', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pipelines.record')),
            ],
            options={
                'indexes': [models.Index(fields=['channel', 'provider_id'], name='communicati_channel_4ec556_idx'), models.Index(fields=['channel', 'external_attendee_id'], name='communicati_channel_8a86f1_idx'), models.Index(fields=['contact_record'], name='communicati_contact_4656c8_idx'), models.Index(fields=['name'], name='communicati_name_0ad261_idx'), models.Index(fields=['last_synced_at'], name='communicati_last_sy_1c6d0a_idx')],
                'unique_together': {('channel', 'external_attendee_id'), ('channel', 'provider_id')},
            },
        ),
    ]
