# Generated by Django 5.0 on 2025-08-22 16:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0014_allow_empty_message_content_for_attachments'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_type', models.CharField(choices=[('comprehensive', 'Comprehensive Sync'), ('chat_specific', 'Chat-Specific Sync'), ('incremental', 'Incremental Sync'), ('historical', 'Historical Sync'), ('recovery', 'Recovery Sync')], max_length=20)),
                ('sync_options', models.JSONField(default=dict, help_text='Sync configuration options (days_back, batch_sizes, etc.)')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('paused', 'Paused')], default='pending', max_length=20)),
                ('celery_task_id', models.CharField(blank=True, help_text='Celery task ID for job management', max_length=255)),
                ('progress', models.JSONField(default=dict, help_text='Current progress state: conversations processed, messages synced, etc.')),
                ('pagination_state', models.JSONField(default=dict, help_text='Cursor positions and pagination state for resuming interrupted syncs')),
                ('result_summary', models.JSONField(default=dict, help_text='Final sync results: totals, errors, performance metrics')),
                ('error_details', models.JSONField(blank=True, help_text='Error information if sync fails', null=True)),
                ('error_count', models.IntegerField(default=0, help_text='Number of errors encountered')),
                ('estimated_duration', models.DurationField(blank=True, help_text='Estimated completion time', null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_progress_update', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(help_text='Channel being synced', on_delete=django.db.models.deletion.CASCADE, to='communications.channel')),
                ('user', models.ForeignKey(help_text='User who initiated the sync', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SyncJobProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phase_name', models.CharField(help_text="Sync phase: 'fetching_conversations', 'processing_messages', etc.", max_length=50)),
                ('step_name', models.CharField(help_text="Specific step within phase: 'batch_1_conversations', 'chat_abc123_messages'", max_length=100)),
                ('items_processed', models.IntegerField(default=0)),
                ('items_total', models.IntegerField(default=0)),
                ('processing_time_ms', models.IntegerField(blank=True, help_text='Time taken for this step in milliseconds', null=True)),
                ('memory_usage_mb', models.FloatField(blank=True, help_text='Memory usage during this step', null=True)),
                ('metadata', models.JSONField(default=dict, help_text='Additional step-specific data (batch info, error details, etc.)')),
                ('step_status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='running', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sync_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_entries', to='communications.syncjob')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddIndex(
            model_name='syncjob',
            index=models.Index(fields=['user', 'status'], name='communicati_user_id_df7d2d_idx'),
        ),
        migrations.AddIndex(
            model_name='syncjob',
            index=models.Index(fields=['channel', 'status'], name='communicati_channel_00c080_idx'),
        ),
        migrations.AddIndex(
            model_name='syncjob',
            index=models.Index(fields=['celery_task_id'], name='communicati_celery__b704be_idx'),
        ),
        migrations.AddIndex(
            model_name='syncjob',
            index=models.Index(fields=['status', 'created_at'], name='communicati_status_c5ef09_idx'),
        ),
        migrations.AddIndex(
            model_name='syncjobprogress',
            index=models.Index(fields=['sync_job', 'phase_name'], name='communicati_sync_jo_30e832_idx'),
        ),
        migrations.AddIndex(
            model_name='syncjobprogress',
            index=models.Index(fields=['sync_job', 'started_at'], name='communicati_sync_jo_0a0073_idx'),
        ),
    ]
