# Generated by Django 5.0 on 2025-08-24 13:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0015_add_background_sync_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='conversation_type',
            field=models.CharField(choices=[('direct', 'Direct Message'), ('group', 'Group Chat'), ('broadcast', 'Broadcast List'), ('channel', 'Channel/Community')], default='direct', help_text='Type of conversation (direct, group, broadcast, channel)', max_length=20),
        ),
        migrations.AddField(
            model_name='conversation',
            name='participant_count',
            field=models.IntegerField(default=0, help_text='Cached count of active participants'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(blank=True, help_text='The attendee who sent this message', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to='communications.chatattendee'),
        ),
        migrations.CreateModel(
            name='ConversationAttendee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True, help_text='When the attendee joined this conversation')),
                ('left_at', models.DateTimeField(blank=True, help_text='When the attendee left (null if still active)', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether attendee is currently in conversation')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('member', 'Member'), ('viewer', 'Viewer')], default='member', help_text='Role in this conversation', max_length=20)),
                ('last_read_at', models.DateTimeField(blank=True, help_text='Last time this attendee read messages', null=True)),
                ('last_typed_at', models.DateTimeField(blank=True, help_text='Last typing indicator timestamp', null=True)),
                ('notification_enabled', models.BooleanField(default=True, help_text='Whether notifications are enabled for this conversation')),
                ('metadata', models.JSONField(default=dict, help_text='Additional attendee-conversation specific data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_participations', to='communications.chatattendee')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_attendees', to='communications.conversation')),
            ],
        ),
        migrations.AddField(
            model_name='conversation',
            name='attendees',
            field=models.ManyToManyField(help_text='Participants in this conversation', related_name='conversations', through='communications.ConversationAttendee', to='communications.chatattendee'),
        ),
        migrations.AddIndex(
            model_name='conversationattendee',
            index=models.Index(fields=['conversation', 'is_active'], name='communicati_convers_b52cbc_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationattendee',
            index=models.Index(fields=['attendee', 'is_active'], name='communicati_attende_336b62_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationattendee',
            index=models.Index(fields=['conversation', 'last_read_at'], name='communicati_convers_5fba4d_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationattendee',
            index=models.Index(fields=['role', 'is_active'], name='communicati_role_576166_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='conversationattendee',
            unique_together={('conversation', 'attendee')},
        ),
    ]
