# Generated by Django 5.0 on 2025-08-27 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0017_add_participant_models'),
        ('pipelines', '0016_update_pipeline_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='secondary_confidence',
            field=models.FloatField(default=0, help_text='Confidence score of secondary resolution'),
        ),
        migrations.AddField(
            model_name='participant',
            name='secondary_pipeline',
            field=models.CharField(blank=True, help_text='Pipeline name of secondary record', max_length=100),
        ),
        migrations.AddField(
            model_name='participant',
            name='secondary_record',
            field=models.ForeignKey(blank=True, help_text='Secondary linked record (e.g., organization via domain matching)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_participants', to='pipelines.record'),
        ),
        migrations.AddField(
            model_name='participant',
            name='secondary_resolution_method',
            field=models.CharField(blank=True, help_text='How the secondary record was resolved', max_length=50),
        ),
    ]
