# Generated by Django 5.0 on 2025-08-28 21:18

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0018_add_secondary_record'),
        ('pipelines', '0016_update_pipeline_types'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordCommunicationProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('communication_identifiers', models.JSONField(default=dict, help_text="{'email': ['john@example.com'], 'phone': ['+27782270354'], 'linkedin': [], 'domain': []}")),
                ('identifier_fields', models.JSONField(default=list, help_text="List of field slugs used as identifiers ['email_address', 'phone_number', 'linkedin_url']")),
                ('sync_status', models.JSONField(default=dict, help_text="{'account_uuid': {'last_sync': '2025-01-28T10:00:00Z', 'status': 'completed', 'message_count': 45}}")),
                ('last_full_sync', models.DateTimeField(blank=True, null=True)),
                ('sync_in_progress', models.BooleanField(default=False)),
                ('sync_error_count', models.IntegerField(default=0)),
                ('last_sync_error', models.TextField(blank=True)),
                ('total_conversations', models.IntegerField(default=0)),
                ('total_messages', models.IntegerField(default=0)),
                ('total_unread', models.IntegerField(default=0)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('auto_sync_enabled', models.BooleanField(default=True, help_text='Automatically sync when record identifiers change')),
                ('sync_frequency_hours', models.IntegerField(default=24, help_text='How often to sync in hours (0 = manual only)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('pipeline', models.ForeignKey(help_text='Pipeline this record belongs to', on_delete=django.db.models.deletion.CASCADE, to='pipelines.pipeline')),
                ('record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='communication_profile', to='pipelines.record')),
            ],
        ),
        migrations.CreateModel(
            name='RecordSyncJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(help_text='Type of sync: full_history, incremental, webhook_trigger', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('progress_percentage', models.IntegerField(default=0)),
                ('current_step', models.CharField(blank=True, max_length=255)),
                ('total_accounts_to_sync', models.IntegerField(default=0)),
                ('accounts_synced', models.IntegerField(default=0)),
                ('messages_found', models.IntegerField(default=0)),
                ('conversations_found', models.IntegerField(default=0)),
                ('new_links_created', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('error_details', models.JSONField(default=dict)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trigger_reason', models.CharField(blank=True, help_text='Why this sync was triggered', max_length=255)),
                ('celery_task_id', models.CharField(blank=True, max_length=255)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_jobs', to='communications.recordcommunicationprofile')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_jobs', to='pipelines.record')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecordCommunicationLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_type', models.CharField(choices=[('email', 'Email Address'), ('phone', 'Phone Number'), ('domain', 'Email Domain'), ('linkedin', 'LinkedIn Profile'), ('manual', 'Manual Link'), ('webhook', 'Webhook Auto-Link')], help_text='How this conversation was linked to the record', max_length=20)),
                ('match_identifier', models.CharField(help_text="The actual identifier that matched (e.g., 'john@example.com')", max_length=255)),
                ('confidence_score', models.FloatField(default=1.0, help_text='Confidence in this match (0.0 to 1.0)')),
                ('linked_at', models.DateTimeField(auto_now_add=True)),
                ('is_primary', models.BooleanField(default=True, help_text='Is this the primary record for this conversation')),
                ('created_by_sync', models.BooleanField(default=False, help_text='Was this link created by automatic sync')),
                ('last_verified', models.DateTimeField(blank=True, help_text='Last time this link was verified as valid', null=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record_links', to='communications.conversation')),
                ('linked_by', models.ForeignKey(blank=True, help_text='User who created this link (null for automatic)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('participant', models.ForeignKey(blank=True, help_text='The participant that links this conversation to the record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='record_links', to='communications.participant')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communication_links', to='pipelines.record')),
            ],
            options={
                'indexes': [models.Index(fields=['record', '-linked_at'], name='communicati_record__f1a4dc_idx'), models.Index(fields=['conversation', 'is_primary'], name='communicati_convers_b52e90_idx'), models.Index(fields=['match_type', 'match_identifier'], name='communicati_match_t_4dbcac_idx'), models.Index(fields=['confidence_score'], name='communicati_confide_9468ff_idx')],
                'unique_together': {('record', 'conversation', 'participant')},
            },
        ),
        migrations.AddIndex(
            model_name='recordcommunicationprofile',
            index=models.Index(fields=['record', '-last_message_at'], name='communicati_record__0dc0d3_idx'),
        ),
        migrations.AddIndex(
            model_name='recordcommunicationprofile',
            index=models.Index(fields=['pipeline', 'sync_in_progress'], name='communicati_pipelin_b0f72f_idx'),
        ),
        migrations.AddIndex(
            model_name='recordcommunicationprofile',
            index=models.Index(fields=['-last_full_sync'], name='communicati_last_fu_e1e9eb_idx'),
        ),
        migrations.AddIndex(
            model_name='recordcommunicationprofile',
            index=django.contrib.postgres.indexes.GinIndex(fields=['communication_identifiers'], name='communicati_communi_5db1ca_gin'),
        ),
        migrations.AddIndex(
            model_name='recordsyncjob',
            index=models.Index(fields=['record', '-created_at'], name='communicati_record__8535a7_idx'),
        ),
        migrations.AddIndex(
            model_name='recordsyncjob',
            index=models.Index(fields=['status', 'created_at'], name='communicati_status_412db9_idx'),
        ),
        migrations.AddIndex(
            model_name='recordsyncjob',
            index=models.Index(fields=['celery_task_id'], name='communicati_celery__9f0227_idx'),
        ),
    ]
