# Generated by Django 5.0 on 2025-08-28 22:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0019_recordcommunicationprofile_recordsyncjob_and_more'),
        ('pipelines', '0016_update_pipeline_types'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='recordcommunicationlink',
            name='communicati_record__f1a4dc_idx',
        ),
        migrations.RenameField(
            model_name='recordcommunicationlink',
            old_name='linked_at',
            new_name='created_at',
        ),
        migrations.AddIndex(
            model_name='recordcommunicationlink',
            index=models.Index(fields=['record', '-created_at'], name='communicati_record__707758_idx'),
        ),
    ]
