# Generated by Django 5.0 on 2025-08-29 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0020_remove_recordcommunicationlink_communicati_record__f1a4dc_idx_and_more'),
        ('pipelines', '0016_update_pipeline_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordcommunicationlink',
            name='match_type',
            field=models.CharField(choices=[('email', 'Email Address'), ('phone', 'Phone Number'), ('domain', 'Email Domain'), ('linkedin', 'LinkedIn Profile'), ('social', 'Social Media Handle'), ('provider_id', 'Provider ID'), ('manual', 'Manual Link'), ('webhook', 'Webhook Auto-Link'), ('other', 'Other')], help_text='How this conversation was linked to the record', max_length=20),
        ),
        migrations.CreateModel(
            name='RecordAttendeeMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendee_id', models.CharField(db_index=True, help_text='UniPile attendee ID from the API', max_length=255)),
                ('provider_id', models.CharField(db_index=True, help_text='Provider-specific ID (e.g., 277203124113@s.whatsapp.net)', max_length=255)),
                ('channel_type', models.CharField(help_text='Channel type: whatsapp, linkedin, instagram, etc.', max_length=20)),
                ('matched_identifier', models.CharField(help_text='Original identifier from record (e.g., +277203124113)', max_length=255)),
                ('identifier_type', models.CharField(help_text='Type of identifier: phone, email, linkedin, etc.', max_length=20)),
                ('attendee_name', models.CharField(blank=True, max_length=255)),
                ('attendee_data', models.JSONField(default=dict, help_text='Full attendee object from UniPile API')),
                ('discovered_at', models.DateTimeField(auto_now_add=True)),
                ('last_verified', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendee_mappings', to='communications.recordcommunicationprofile')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendee_mappings', to='pipelines.record')),
            ],
            options={
                'indexes': [models.Index(fields=['provider_id', 'channel_type'], name='communicati_provide_fbbd6b_idx'), models.Index(fields=['record', 'channel_type'], name='communicati_record__f3ccdc_idx'), models.Index(fields=['matched_identifier', 'identifier_type'], name='communicati_matched_98bb4f_idx')],
                'unique_together': {('record', 'attendee_id', 'channel_type')},
            },
        ),
    ]
