# Generated by Django 5.0 on 2025-08-30 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0021_add_record_attendee_mapping'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='conversationattendee',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='conversationattendee',
            name='attendee',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='attendees',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='conversationattendee',
            name='conversation',
        ),
        migrations.RemoveField(
            model_name='syncjob',
            name='channel',
        ),
        migrations.RemoveField(
            model_name='syncjob',
            name='user',
        ),
        migrations.RemoveField(
            model_name='syncjobprogress',
            name='sync_job',
        ),
        migrations.DeleteModel(
            name='ChatAttendee',
        ),
        migrations.DeleteModel(
            name='ConversationAttendee',
        ),
        migrations.DeleteModel(
            name='SyncJob',
        ),
        migrations.DeleteModel(
            name='SyncJobProgress',
        ),
    ]
