# Generated by Django 5.0 on 2025-09-04 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0025_add_name_field_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantsettings',
            name='name_mapping_mode',
            field=models.CharField(blank=True, choices=[('single', 'Single name field'), ('split', 'Split name fields')], default='', help_text='Whether to use single or split name fields', max_length=20),
        ),
    ]
