# Generated by Django 5.0 on 2025-09-04 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0026_add_name_mapping_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantsettings',
            name='company_name_field',
            field=models.CharField(blank=True, default='', help_text='Field slug for company/organization name', max_length=100),
        ),
    ]
