# Generated by Django 5.0 on 2025-09-09 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0030_remove_old_required_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='channel_type',
            field=models.CharField(choices=[('linkedin', 'LinkedIn'), ('gmail', 'Gmail'), ('outlook', 'Outlook'), ('mail', 'Email (Generic)'), ('whatsapp', 'WhatsApp'), ('instagram', 'Instagram'), ('messenger', 'Facebook Messenger'), ('telegram', 'Telegram'), ('twitter', 'Twitter/X'), ('scheduling', 'Scheduling'), ('calendar', 'Calendar')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userchannelconnection',
            name='channel_type',
            field=models.CharField(choices=[('linkedin', 'LinkedIn'), ('gmail', 'Gmail'), ('outlook', 'Outlook'), ('mail', 'Email (Generic)'), ('whatsapp', 'WhatsApp'), ('instagram', 'Instagram'), ('messenger', 'Facebook Messenger'), ('telegram', 'Telegram'), ('twitter', 'Twitter/X'), ('scheduling', 'Scheduling'), ('calendar', 'Calendar')], max_length=20),
        ),
    ]
