# Generated by Django 5.0 on 2025-09-09 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0032_add_scheduling_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulingprofile',
            name='channel',
            field=models.ForeignKey(blank=True, help_text='Calendar channel for availability checking', limit_choices_to={'channel_type__in': ['calendar', 'gmail', 'outlook', 'scheduling']}, null=True, on_delete=django.db.models.deletion.CASCADE, to='communications.channel'),
        ),
    ]
