# Generated by Django 5.0 on 2025-09-09 13:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0033_make_channel_optional_in_scheduling'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='schedulingprofile',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='schedulingprofile',
            index=models.Index(fields=['user'], name='scheduling_user_idx'),
        ),
    ]
