# Generated by Django 5.0 on 2025-09-09 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0034_remove_unique_constraint_scheduling'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='schedulingprofile',
            name='communicati_channel_f61ab2_idx',
        ),
        migrations.RemoveField(
            model_name='schedulingprofile',
            name='channel',
        ),
        migrations.AddField(
            model_name='schedulingprofile',
            name='calendar_connection',
            field=models.ForeignKey(blank=True, help_text="User's connected calendar account (Google/Outlook via UniPile)", limit_choices_to={'channel_type__in': ['calendar', 'gmail', 'outlook']}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheduling_profile', to='communications.userchannelconnection'),
        ),
        migrations.AddIndex(
            model_name='schedulingprofile',
            index=models.Index(fields=['calendar_connection'], name='communicati_calenda_e63362_idx'),
        ),
    ]
