# Generated by Django 5.0 on 2025-09-09 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0035_remove_schedulingprofile_communicati_channel_f61ab2_idx_and_more'),
        ('pipelines', '0018_add_assigned_user_ids_with_trigger'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingtype',
            name='calendar_connection',
            field=models.ForeignKey(blank=True, help_text='Calendar account to check availability and create events', limit_choices_to={'channel_type__in': ['calendar', 'gmail', 'outlook']}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meeting_types', to='communications.userchannelconnection'),
        ),
        migrations.AddField(
            model_name='meetingtype',
            name='calendar_id',
            field=models.CharField(blank=True, default='', help_text='Specific calendar ID within the account for this meeting type', max_length=255),
        ),
        migrations.AlterField(
            model_name='meetingtype',
            name='slug',
            field=models.SlugField(help_text='Clean URL for this meeting type', max_length=100),
        ),
        migrations.AddIndex(
            model_name='meetingtype',
            index=models.Index(fields=['calendar_connection'], name='communicati_calenda_02b4f0_idx'),
        ),
    ]
