# Generated by Django 5.0 on 2025-09-09 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0036_add_calendar_and_slug_to_meeting_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingtype',
            name='calendar_name',
            field=models.CharField(blank=True, default='', help_text='Name of the selected calendar for display purposes', max_length=255),
        ),
    ]
