# Generated by Django 5.0 on 2025-09-10 06:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0037_add_calendar_name_to_meeting_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulingprofile',
            name='slot_interval_minutes',
            field=models.IntegerField(choices=[(15, '15 minutes'), (20, '20 minutes'), (30, '30 minutes'), (45, '45 minutes'), (60, '60 minutes')], default=30, help_text='Time interval for generating available slots', validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(60)]),
        ),
    ]
