# Generated by Django 5.0 on 2025-09-10 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0038_add_slot_interval'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='meetingtype',
            name='communicati_calenda_02b4f0_idx',
        ),
        migrations.RemoveField(
            model_name='meetingtype',
            name='calendar_connection',
        ),
    ]
