# Generated by Django 5.0 on 2025-09-10 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0039_remove_calendar_connection_from_meeting_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingtype',
            name='created_for_org',
            field=models.BooleanField(default=False, help_text='Whether this template is available organization-wide'),
        ),
        migrations.AddField(
            model_name='meetingtype',
            name='is_template',
            field=models.BooleanField(default=False, help_text='Whether this is a template for others to copy'),
        ),
        migrations.AddField(
            model_name='meetingtype',
            name='template_source',
            field=models.ForeignKey(blank=True, help_text='The template this meeting type was copied from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copied_instances', to='communications.meetingtype'),
        ),
    ]
