# Generated by Django 5.0 on 2025-09-10 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0040_add_template_fields_to_meeting_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingtype',
            name='is_synced_to_template',
            field=models.BooleanField(default=False, help_text='Whether this meeting type stays synced with its template'),
        ),
        migrations.AddField(
            model_name='meetingtype',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, help_text='When this was last synced with its template', null=True),
        ),
        migrations.AddField(
            model_name='meetingtype',
            name='template_type',
            field=models.CharField(blank=True, choices=[('standalone', 'Standalone - One-time copy'), ('centralized', 'Centralized - Stays synced')], help_text='How the template behaves when used', max_length=20, null=True),
        ),
    ]
