# Generated by Django 5.0 on 2025-09-12 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0041_add_template_type_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='conversation_type',
            field=models.CharField(choices=[('direct', 'Direct Message'), ('group', 'Group Chat'), ('broadcast', 'Broadcast List'), ('channel', 'Channel/Community'), ('calendar_event', 'Calendar Event')], default='direct', help_text='Type of conversation (direct, group, broadcast, channel)', max_length=20),
        ),
    ]
