# Generated by Django 5.0 on 2025-09-12 20:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0042_add_calendar_event_conversation_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingtype',
            name='facilitator_settings',
            field=models.JSONField(blank=True, default=dict, help_text='Settings for facilitator meeting mode'),
        ),
        migrations.AddField(
            model_name='meetingtype',
            name='meeting_mode',
            field=models.CharField(choices=[('direct', 'Direct Meeting'), ('facilitator', 'Facilitator Meeting')], default='direct', help_text='Direct: Regular 1-on-1 booking. Facilitator: Coordinate meeting between two other people', max_length=20),
        ),
        migrations.CreateModel(
            name='FacilitatorBooking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('participant_1_email', models.EmailField(max_length=254)),
                ('participant_1_name', models.CharField(max_length=255)),
                ('participant_1_phone', models.CharField(blank=True, max_length=50)),
                ('participant_1_data', models.JSONField(blank=True, default=dict)),
                ('selected_duration_minutes', models.IntegerField()),
                ('selected_location_type', models.CharField(choices=[('zoom', 'Zoom'), ('google_meet', 'Google Meet'), ('teams', 'Microsoft Teams'), ('phone', 'Phone Call'), ('in_person', 'In Person'), ('custom', 'Custom Location')], max_length=50)),
                ('selected_location_details', models.JSONField(blank=True, default=dict)),
                ('selected_slots', models.JSONField(default=list)),
                ('participant_1_completed_at', models.DateTimeField()),
                ('participant_1_message', models.TextField(blank=True)),
                ('participant_2_email', models.EmailField(max_length=254)),
                ('participant_2_name', models.CharField(blank=True, max_length=255)),
                ('participant_2_phone', models.CharField(blank=True, max_length=50)),
                ('participant_2_data', models.JSONField(blank=True, null=True)),
                ('final_slot', models.JSONField(blank=True, null=True)),
                ('participant_2_completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending_p2', 'Pending Participant 2'), ('completed', 'Completed'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending_p2', max_length=20)),
                ('unique_token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('invitation_sent_at', models.DateTimeField(blank=True, null=True)),
                ('invitation_opened_at', models.DateTimeField(blank=True, null=True)),
                ('reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facilitator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facilitated_bookings', to=settings.AUTH_USER_MODEL)),
                ('meeting_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facilitator_bookings', to='communications.meetingtype')),
                ('scheduled_meeting', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facilitator_booking', to='communications.scheduledmeeting')),
            ],
            options={
                'indexes': [models.Index(fields=['unique_token'], name='communicati_unique__5b30be_idx'), models.Index(fields=['meeting_type', 'status'], name='communicati_meeting_8dd607_idx'), models.Index(fields=['expires_at'], name='communicati_expires_8468c6_idx'), models.Index(fields=['facilitator'], name='communicati_facilit_9547ff_idx')],
            },
        ),
    ]
