# Generated by Django 5.0 on 2025-09-13 08:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0043_add_facilitator_meeting_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilitatorbooking',
            name='participant_1_record_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='facilitatorbooking',
            name='participant_1_token',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AddField(
            model_name='facilitatorbooking',
            name='participant_2_record_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='facilitatorbooking',
            name='participant_2_token',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name='facilitatorbooking',
            name='participant_1_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='facilitatorbooking',
            name='selected_duration_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='facilitatorbooking',
            name='selected_location_type',
            field=models.CharField(blank=True, choices=[('zoom', 'Zoom'), ('google_meet', 'Google Meet'), ('teams', 'Microsoft Teams'), ('phone', 'Phone Call'), ('in_person', 'In Person'), ('custom', 'Custom Location')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='facilitatorbooking',
            name='status',
            field=models.CharField(choices=[('pending_p1', 'Pending Participant 1'), ('pending_p2', 'Pending Participant 2'), ('completed', 'Completed'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending_p1', max_length=20),
        ),
    ]
