# Generated by Django 5.0 on 2025-09-16 06:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_add_organization_website'),
        ('workflows', '0003_add_missing_triggers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflowtrigger',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='workflowtrigger',
            name='workflow',
        ),
        migrations.RemoveIndex(
            model_name='workflow',
            name='workflows_w_status_6c6375_idx',
        ),
        migrations.RemoveField(
            model_name='workflow',
            name='trigger_config',
        ),
        migrations.RemoveField(
            model_name='workflow',
            name='trigger_type',
        ),
        migrations.AlterField(
            model_name='workflowexecutionlog',
            name='node_type',
            field=models.CharField(choices=[('ai_prompt', 'AI Prompt'), ('ai_analysis', 'AI Analysis'), ('ai_classification', 'AI Classification'), ('ai_conversation_loop', 'AI Conversation Loop'), ('record_create', 'Create Record'), ('record_update', 'Update Record'), ('record_delete', 'Delete Record'), ('record_find', 'Find Records'), ('condition', 'Condition (If/Else)'), ('for_each', 'For Each (Loop)'), ('wait_delay', 'Wait/Delay'), ('wait_for_response', 'Wait for Response'), ('wait_for_record_event', 'Wait for Record Event'), ('wait_for_condition', 'Wait for Condition'), ('http_request', 'HTTP Request'), ('webhook_out', 'Send Webhook'), ('approval', 'Human Approval'), ('task_notify', 'Task/Notification'), ('sub_workflow', 'Sub-workflow Call'), ('reusable_workflow', 'Reusable Workflow'), ('merge_data', 'Merge Data'), ('unipile_send_email', 'Send Email via UniPile'), ('unipile_send_linkedin', 'Send LinkedIn Message'), ('unipile_send_whatsapp', 'Send WhatsApp Message'), ('unipile_send_sms', 'Send SMS'), ('unipile_sync_messages', 'Sync UniPile Messages'), ('log_communication', 'Log Communication Activity'), ('resolve_contact', 'Resolve/Create Contact Record'), ('update_contact_status', 'Update Contact Status'), ('create_follow_up_task', 'Create Follow-up Task'), ('analyze_communication', 'Analyze Communication Patterns'), ('score_engagement', 'Score Contact Engagement')], max_length=30),
        ),
        migrations.AddIndex(
            model_name='workflow',
            index=models.Index(fields=['status'], name='workflows_w_status_9d48f8_idx'),
        ),
        migrations.DeleteModel(
            name='WorkflowTrigger',
        ),
    ]
