# Generated by Django 5.0 on 2025-08-12 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duplicates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlextractionrule',
            name='normalization_steps',
            field=models.JSONField(blank=True, default=list, help_text='Visual normalization steps configuration'),
        ),
    ]
