# Generated by Django 5.0 on 2025-08-13 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duplicates', '0002_add_normalization_steps_to_url_extraction_rule'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlextractionrule',
            name='template_type',
            field=models.CharField(blank=True, help_text="Template type used to create this rule (e.g., 'linkedin', 'domain', 'custom')", max_length=50, null=True),
        ),
    ]
