# Generated by Django 5.0 on 2025-08-13 09:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duplicates', '0004_populate_template_types'),
        ('pipelines', '0010_remove_fieldgroup_is_collapsed'),
        ('tenants', '0002_tenantmaintenance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='urlextractionrule',
            name='duplicates__tenant__4575e4_idx',
        ),
        migrations.AlterUniqueTogether(
            name='urlextractionrule',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='urlextractionrule',
            name='pipeline',
            field=models.ForeignKey(blank=True, help_text='Pipeline this URL extraction rule applies to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='url_extraction_rules', to='pipelines.pipeline'),
        ),
        migrations.AlterUniqueTogether(
            name='urlextractionrule',
            unique_together={('pipeline', 'name')},
        ),
        migrations.AddIndex(
            model_name='urlextractionrule',
            index=models.Index(fields=['tenant', 'pipeline'], name='duplicates__tenant__0fe38d_idx'),
        ),
        migrations.AddIndex(
            model_name='urlextractionrule',
            index=models.Index(fields=['pipeline', 'is_active'], name='duplicates__pipelin_1155f7_idx'),
        ),
    ]
