# Generated by Django 5.0 on 2025-08-13 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duplicates', '0009_make_pipeline_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duplicateresolution',
            name='action_taken',
            field=models.CharField(choices=[('merge', 'Merge Records'), ('keep_both', 'Keep Both Records'), ('ignore', 'Mark as False Positive'), ('manual_review', 'Requires Manual Review'), ('rollback', 'Rollback Resolution')], max_length=50),
        ),
    ]
