# Generated by Django 5.0 on 2025-07-31 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='field',
            name='placeholder',
        ),
        migrations.RemoveField(
            model_name='field',
            name='width',
        ),
    ]
