# Generated by Django 5.0 on 2025-08-01 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0002_remove_field_placeholder_remove_field_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='form_validation_rules',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='field',
            name='is_visible_in_public_forms',
            field=models.BooleanField(default=False),
        ),
    ]
