# Generated by Django 5.0 on 2025-08-02 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0004_update_pipeline_access_levels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipeline',
            name='access_level',
            field=models.CharField(choices=[('private', 'Private'), ('internal', 'Internal'), ('public', 'Public')], default='internal', max_length=20),
        ),
    ]
