# Generated by Django 5.0 on 2025-08-06 13:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0005_update_access_level_default'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='field',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_fields', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='field',
            name='hard_delete_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='field',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='field',
            name='scheduled_for_hard_delete',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='field',
            index=models.Index(fields=['is_deleted'], name='pipelines_f_is_dele_f0017b_idx'),
        ),
        migrations.AddIndex(
            model_name='field',
            index=models.Index(fields=['scheduled_for_hard_delete'], name='pipelines_f_schedul_f2103c_idx'),
        ),
        migrations.AddIndex(
            model_name='field',
            index=models.Index(fields=['pipeline', 'is_deleted'], name='idx_field_pipeline_active'),
        ),
        migrations.AddIndex(
            model_name='field',
            index=models.Index(fields=['is_deleted', 'deleted_at'], name='idx_field_deletion_status'),
        ),
    ]
