# Generated by Django 5.0 on 2025-08-11 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0007_alter_field_field_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='field_type',
            field=models.CharField(choices=[('text', 'text'), ('textarea', 'textarea'), ('number', 'number'), ('boolean', 'boolean'), ('date', 'date'), ('phone', 'phone'), ('email', 'email'), ('address', 'address'), ('select', 'select'), ('multiselect', 'multiselect'), ('tags', 'tags'), ('url', 'url'), ('file', 'file'), ('button', 'button'), ('relation', 'relation'), ('user', 'user'), ('ai_generated', 'ai_generated')], max_length=50),
        ),
    ]
