# Generated by Django 5.0 on 2025-08-12 08:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0008_remove_record_data_field_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(default='#3B82F6', help_text='Hex color code', max_length=7)),
                ('icon', models.CharField(default='folder', help_text='Icon identifier', max_length=50)),
                ('display_order', models.IntegerField(default=0)),
                ('is_collapsed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_field_groups', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_field_groups', to=settings.AUTH_USER_MODEL)),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_groups', to='pipelines.pipeline')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_field_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pipelines_fieldgroup',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='field',
            name='field_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fields', to='pipelines.fieldgroup'),
        ),
        migrations.AddIndex(
            model_name='fieldgroup',
            index=models.Index(fields=['pipeline'], name='pipelines_f_pipelin_6cdd34_idx'),
        ),
        migrations.AddIndex(
            model_name='fieldgroup',
            index=models.Index(fields=['display_order'], name='pipelines_f_display_ae2bef_idx'),
        ),
        migrations.AddIndex(
            model_name='fieldgroup',
            index=models.Index(fields=['is_deleted'], name='pipelines_f_is_dele_57809b_idx'),
        ),
        migrations.AddIndex(
            model_name='fieldgroup',
            index=models.Index(condition=models.Q(('is_deleted', False)), fields=['pipeline', 'display_order'], name='idx_fieldgroup_pipe_order'),
        ),
        migrations.AddConstraint(
            model_name='fieldgroup',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('pipeline', 'name'), name='unique_fieldgroup_name_per_pipeline'),
        ),
    ]
