# Generated by Django 5.0 on 2025-08-12 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0009_fieldgroup_field_field_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fieldgroup',
            name='is_collapsed',
        ),
    ]
