# Generated by Django 5.0 on 2025-08-14 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0010_remove_fieldgroup_is_collapsed'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='is_visible_in_shared_list_and_detail_views',
            field=models.BooleanField(default=False),
        ),
    ]
