# Generated by Django 5.0 on 2025-08-14 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0012_add_saved_filter_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipeline',
            name='filter_management_settings',
            field=models.JSONField(default=dict, help_text='Settings for filter management in this pipeline'),
        ),
        migrations.AddField(
            model_name='savedfilter',
            name='access_level',
            field=models.CharField(choices=[('private', 'Private'), ('pipeline_users', 'Pipeline Users'), ('public_shareable', 'Public Shareable')], default='private', help_text='Who can access this filter', max_length=20),
        ),
    ]
