# Generated by Django 5.0 on 2025-08-14 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0013_add_filter_access_levels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedfilter',
            name='access_level',
            field=models.CharField(choices=[('private', 'Private'), ('pipeline_users', 'Pipeline Users')], default='private', help_text='Who can access this filter', max_length=20),
        ),
    ]
