# Generated by Django 5.0 on 2025-08-14 17:39

from django.db import migrations


def migrate_public_shareable_filters(apps, schema_editor):
    """
    Migrate existing 'public_shareable' filters to 'pipeline_users'
    since we're removing the public_shareable option
    """
    SavedFilter = apps.get_model('pipelines', 'SavedFilter')
    
    # Update any existing public_shareable filters to pipeline_users
    updated_count = SavedFilter.objects.filter(
        access_level='public_shareable'
    ).update(access_level='pipeline_users')
    
    if updated_count > 0:
        print(f"Migrated {updated_count} public_shareable filters to pipeline_users")


def reverse_migrate_public_shareable_filters(apps, schema_editor):
    """
    Reverse migration - convert pipeline_users back to public_shareable
    (Note: This is not perfect as we lose information about which were originally pipeline_users)
    """
    # We can't perfectly reverse this migration since we don't know which filters
    # were originally pipeline_users vs public_shareable
    # So we'll leave them as pipeline_users
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0014_update_filter_access_levels'),
    ]

    operations = [
        migrations.RunPython(
            migrate_public_shareable_filters,
            reverse_migrate_public_shareable_filters,
        ),
    ]
