# Generated by Django 5.0 on 2025-08-17 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0015_migrate_public_shareable_filters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipeline',
            name='pipeline_type',
            field=models.CharField(choices=[('contacts', 'Contacts & People'), ('companies', 'Companies & Organizations'), ('deals', 'Deals & Opportunities'), ('inventory', 'Inventory & Assets'), ('support', 'Support & Tickets'), ('custom', 'Custom')], default='custom', max_length=50),
        ),
    ]
