# Generated by Django 5.0 on 2025-09-18 11:45

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0018_add_assigned_user_ids_with_trigger'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('form_id', models.CharField(help_text="ID of the form configuration used (e.g., 'pipeline_23_internal_full')", max_length=255)),
                ('form_name', models.CharField(help_text='Human-readable name of the form at submission time', max_length=255)),
                ('form_mode', models.CharField(choices=[('internal_full', 'Internal Full Access'), ('internal_filtered', 'Internal Filtered'), ('public_full', 'Public Full'), ('public_filtered', 'Public Filtered'), ('stage_internal', 'Stage Internal'), ('stage_public', 'Stage Public'), ('shared_record', 'Shared Record Form')], default='internal_full', help_text='The form mode used for submission', max_length=50)),
                ('submitted_data', models.JSONField(default=dict, help_text='Raw form data as submitted (before processing)')),
                ('processed_data', models.JSONField(default=dict, help_text='Processed data after validation and transformation')),
                ('form_config', models.JSONField(default=dict, help_text='Snapshot of form configuration at submission time')),
                ('visible_fields', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, help_text='Fields that were visible in the form', size=None)),
                ('required_fields', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, help_text='Fields that were required in the form', size=None)),
                ('submission_source', models.CharField(choices=[('web', 'Web Form'), ('api', 'API'), ('import', 'Import'), ('workflow', 'Workflow'), ('mobile', 'Mobile App'), ('email', 'Email')], default='web', help_text='Source of the submission', max_length=50)),
                ('submission_url', models.URLField(blank=True, help_text='URL where the form was submitted from')),
                ('is_anonymous', models.BooleanField(default=False, help_text='Whether this was an anonymous submission')),
                ('session_id', models.CharField(blank=True, help_text='Session ID for tracking anonymous submissions', max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of submitter', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent string of submitter')),
                ('referrer', models.URLField(blank=True, help_text='Referrer URL')),
                ('validation_errors', models.JSONField(default=list, help_text='Any validation errors encountered')),
                ('processing_time_ms', models.IntegerField(blank=True, help_text='Time taken to process submission in milliseconds', null=True)),
                ('spam_score', models.FloatField(blank=True, help_text='Spam detection score (0-1)', null=True)),
                ('captcha_verified', models.BooleanField(default=False, help_text='Whether captcha was verified (if applicable)')),
                ('utm_source', models.CharField(blank=True, max_length=255)),
                ('utm_medium', models.CharField(blank=True, max_length=255)),
                ('utm_campaign', models.CharField(blank=True, max_length=255)),
                ('utm_term', models.CharField(blank=True, max_length=255)),
                ('utm_content', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('record', models.ForeignKey(help_text='The record created from this form submission', on_delete=django.db.models.deletion.CASCADE, related_name='form_submissions', to='pipelines.record')),
                ('submitted_by', models.ForeignKey(blank=True, help_text='Authenticated user who submitted (null for anonymous)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pipelines_formsubmission',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['form_id'], name='pipelines_f_form_id_21513a_idx'), models.Index(fields=['submission_source'], name='pipelines_f_submiss_e6df7e_idx'), models.Index(fields=['created_at'], name='pipelines_f_created_d35b94_idx'), models.Index(fields=['submitted_by'], name='pipelines_f_submitt_39a9da_idx'), models.Index(fields=['is_anonymous'], name='pipelines_f_is_anon_f8aa3b_idx'), models.Index(fields=['session_id'], name='pipelines_f_session_58d74c_idx')],
            },
        ),
    ]
