# Generated by Django 5.0 on 2025-09-18 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0019_add_formsubmission_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formsubmission',
            name='required_fields',
        ),
        migrations.RemoveField(
            model_name='formsubmission',
            name='visible_fields',
        ),
    ]
