# Generated by Django 5.0 on 2025-09-30 12:33

import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0020_remove_visible_required_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='auto_reverse_config',
            field=models.JSONField(default=dict, help_text='Configuration for automatic reverse field creation'),
        ),
        migrations.AddField(
            model_name='field',
            name='is_auto_generated',
            field=models.BooleanField(default=False, help_text='True if this field was automatically created as a reverse relation'),
        ),
        migrations.AddField(
            model_name='field',
            name='reverse_field_id',
            field=models.IntegerField(blank=True, help_text='ID of the reverse relation field (bidirectional link)', null=True),
        ),
        migrations.AddIndex(
            model_name='field',
            index=models.Index(fields=['is_auto_generated'], name='pipelines_f_is_auto_53dd9e_idx'),
        ),
        migrations.AddIndex(
            model_name='field',
            index=models.Index(fields=['reverse_field_id'], name='pipelines_f_reverse_c09ada_idx'),
        ),
        migrations.AddIndex(
            model_name='field',
            index=models.Index(fields=['field_type', 'is_auto_generated'], name='idx_field_type_auto_gen'),
        ),
        migrations.AddIndex(
            model_name='field',
            index=django.contrib.postgres.indexes.GinIndex(fields=['auto_reverse_config'], name='pipelines_f_auto_re_fb462f_gin'),
        ),
    ]
