# Generated by Django 5.0 on 2025-07-29 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='ai_config_encrypted',
            field=models.TextField(blank=True, help_text='Encrypted AI configuration including API keys', null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='ai_current_usage',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Current month AI usage in USD', max_digits=10),
        ),
        migrations.AddField(
            model_name='tenant',
            name='ai_enabled',
            field=models.BooleanField(default=False, help_text='Enable AI features for this tenant'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='ai_usage_limit',
            field=models.DecimalField(decimal_places=2, default=100.0, help_text='Monthly AI usage limit in USD', max_digits=10),
        ),
    ]
