# Generated by Django 5.0 on 2025-09-12 14:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='Checklist item text', max_length=500)),
                ('is_completed', models.BooleanField(default=False, help_text='Whether this checklist item is completed')),
                ('completed_at', models.DateTimeField(blank=True, help_text='When this item was completed', null=True)),
                ('order', models.IntegerField(default=0, help_text='Display order within the task')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_by', models.ForeignKey(blank=True, help_text='User who completed this item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_checklist_items', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(help_text='Parent task', on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='tasks.task')),
            ],
            options={
                'verbose_name': 'Task Checklist Item',
                'verbose_name_plural': 'Task Checklist Items',
                'ordering': ['order', 'created_at'],
                'indexes': [models.Index(fields=['task', 'order'], name='tasks_taskc_task_id_7fd65a_idx'), models.Index(fields=['task', 'is_completed'], name='tasks_taskc_task_id_950de8_idx')],
            },
        ),
    ]
