# Generated by Django 5.0 on 2025-08-13 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pipelines', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('encrypted_token', models.CharField(db_index=True, max_length=500, unique=True)),
                ('access_mode', models.CharField(choices=[('readonly', 'Read-only'), ('editable', 'Editable')], default='editable', max_length=10)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('access_count', models.PositiveIntegerField(default=0)),
                ('last_accessed_at', models.DateTimeField(blank=True, null=True)),
                ('last_accessed_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='pipelines.record')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_shares', to=settings.AUTH_USER_MODEL)),
                ('shared_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sharing_shared_records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SharedRecordAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessed_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('session_duration', models.PositiveIntegerField(blank=True, help_text='Session duration in seconds', null=True)),
                ('shared_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='sharing.sharedrecord')),
            ],
            options={
                'db_table': 'sharing_shared_record_access',
                'ordering': ['-accessed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='sharedrecord',
            index=models.Index(fields=['encrypted_token'], name='sharing_sha_encrypt_9a37b1_idx'),
        ),
        migrations.AddIndex(
            model_name='sharedrecord',
            index=models.Index(fields=['record', 'shared_by'], name='sharing_sha_record__bd4e97_idx'),
        ),
        migrations.AddIndex(
            model_name='sharedrecord',
            index=models.Index(fields=['expires_at'], name='sharing_sha_expires_fb3dab_idx'),
        ),
        migrations.AddIndex(
            model_name='sharedrecord',
            index=models.Index(fields=['is_active', 'expires_at'], name='sharing_sha_is_acti_f6aeb0_idx'),
        ),
        migrations.AddIndex(
            model_name='sharedrecord',
            index=models.Index(fields=['shared_by', 'created_at'], name='sharing_sha_shared__b9c1b5_idx'),
        ),
        migrations.AddIndex(
            model_name='sharedrecordaccess',
            index=models.Index(fields=['shared_record', 'accessed_at'], name='sharing_sha_shared__b6e89e_idx'),
        ),
        migrations.AddIndex(
            model_name='sharedrecordaccess',
            index=models.Index(fields=['accessed_at'], name='sharing_sha_accesse_be0968_idx'),
        ),
        migrations.AddIndex(
            model_name='sharedrecordaccess',
            index=models.Index(fields=['ip_address'], name='sharing_sha_ip_addr_c66b8e_idx'),
        ),
    ]
