# Generated by Django 5.0 on 2025-08-13 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0001_initial'),
    ]

    operations = [
    ]
