# Generated by Django 5.0 on 2025-08-13 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0002_force_sharing_models'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='sharedrecord',
            new_name='sharing_sha_encrypt_17df5e_idx',
            old_name='sharing_sha_encrypt_9a37b1_idx',
        ),
        migrations.RenameIndex(
            model_name='sharedrecord',
            new_name='sharing_sha_record__d92a43_idx',
            old_name='sharing_sha_record__bd4e97_idx',
        ),
        migrations.RenameIndex(
            model_name='sharedrecord',
            new_name='sharing_sha_expires_bd6fbc_idx',
            old_name='sharing_sha_expires_fb3dab_idx',
        ),
        migrations.RenameIndex(
            model_name='sharedrecord',
            new_name='sharing_sha_is_acti_70588a_idx',
            old_name='sharing_sha_is_acti_f6aeb0_idx',
        ),
        migrations.RenameIndex(
            model_name='sharedrecord',
            new_name='sharing_sha_shared__4bfac6_idx',
            old_name='sharing_sha_shared__b9c1b5_idx',
        ),
        migrations.RenameIndex(
            model_name='sharedrecordaccess',
            new_name='sharing_sha_shared__a4d727_idx',
            old_name='sharing_sha_shared__b6e89e_idx',
        ),
        migrations.RenameIndex(
            model_name='sharedrecordaccess',
            new_name='sharing_sha_accesse_2a3f66_idx',
            old_name='sharing_sha_accesse_be0968_idx',
        ),
        migrations.RenameIndex(
            model_name='sharedrecordaccess',
            new_name='sharing_sha_ip_addr_fdd08f_idx',
            old_name='sharing_sha_ip_addr_c66b8e_idx',
        ),
    ]
