# Generated by Django 5.0 on 2025-08-13 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0003_rename_sharing_sha_encrypt_9a37b1_idx_sharing_sha_encrypt_17df5e_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedrecordaccess',
            name='accessor_email',
            field=models.EmailField(blank=True, help_text='Email of the person accessing the shared record', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='sharedrecordaccess',
            name='accessor_name',
            field=models.CharField(blank=True, help_text='Name of the person accessing the shared record', max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='sharedrecordaccess',
            index=models.Index(fields=['accessor_email'], name='sharing_sha_accesso_69a6a1_idx'),
        ),
        migrations.AddIndex(
            model_name='sharedrecordaccess',
            index=models.Index(fields=['accessor_name', 'accessor_email'], name='sharing_sha_accesso_224e9e_idx'),
        ),
    ]
