# Generated by Django 5.0 on 2025-08-13 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0004_add_accessor_fields'),
    ]

    operations = [
        # First, populate any existing null values with default data
        migrations.RunSQL(
            "UPDATE sharing_shared_record_access SET accessor_name = 'Unknown User' WHERE accessor_name IS NULL;",
            reverse_sql="UPDATE sharing_shared_record_access SET accessor_name = NULL WHERE accessor_name = 'Unknown User';"
        ),
        migrations.RunSQL(
            "UPDATE sharing_shared_record_access SET accessor_email = 'unknown@example.com' WHERE accessor_email IS NULL;",
            reverse_sql="UPDATE sharing_shared_record_access SET accessor_email = NULL WHERE accessor_email = 'unknown@example.com';"
        ),
        
        # Then alter the fields to be non-nullable
        migrations.AlterField(
            model_name='sharedrecordaccess',
            name='accessor_name',
            field=models.CharField(max_length=255, help_text='Name of the person accessing the shared record'),
        ),
        migrations.AlterField(
            model_name='sharedrecordaccess',
            name='accessor_email',
            field=models.EmailField(help_text='Email of the person accessing the shared record'),
        ),
    ]
