# Generated by Django 5.0 on 2025-08-14 00:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0012_add_saved_filter_model'),
        ('sharing', '0006_add_intended_recipient_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_token', models.CharField(db_index=True, help_text='Encrypted token for secure access', max_length=500, unique=True)),
                ('intended_recipient_email', models.EmailField(help_text='Email address of the intended recipient who can access this share', max_length=254)),
                ('access_mode', models.CharField(choices=[('readonly', 'Read-only'), ('filtered_edit', 'Filtered Edit')], default='readonly', max_length=15)),
                ('expires_at', models.DateTimeField(help_text='When this share link expires')),
                ('access_count', models.PositiveIntegerField(default=0, help_text='Number of times this share has been accessed')),
                ('last_accessed_at', models.DateTimeField(blank=True, help_text='When this share was last accessed', null=True)),
                ('last_accessed_ip', models.GenericIPAddressField(blank=True, help_text='IP address of last access', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this share is currently active')),
                ('revoked_at', models.DateTimeField(blank=True, help_text='When this share was revoked', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'sharing_sharedfilter',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='sharedrecord',
            new_name='sharing_sha_intende_22e729_idx',
            old_name='sharing_sha_intende_ed73a0_idx',
        ),
        migrations.RenameIndex(
            model_name='sharedrecord',
            new_name='sharing_sha_intende_78402d_idx',
            old_name='sharing_sha_intende_7f2b45_idx',
        ),
        migrations.AddField(
            model_name='sharedfilter',
            name='revoked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_filter_shares', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sharedfilter',
            name='saved_filter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='pipelines.savedfilter'),
        ),
        migrations.AddField(
            model_name='sharedfilter',
            name='shared_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_filters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='sharedfilter',
            index=models.Index(fields=['encrypted_token'], name='sharing_sha_encrypt_18327a_idx'),
        ),
        migrations.AddIndex(
            model_name='sharedfilter',
            index=models.Index(fields=['saved_filter', 'shared_by'], name='sharing_sha_saved_f_3248b2_idx'),
        ),
        migrations.AddIndex(
            model_name='sharedfilter',
            index=models.Index(fields=['expires_at'], name='sharing_sha_expires_8ef86b_idx'),
        ),
        migrations.AddIndex(
            model_name='sharedfilter',
            index=models.Index(fields=['is_active', 'expires_at'], name='sharing_sha_is_acti_c2e906_idx'),
        ),
        migrations.AddIndex(
            model_name='sharedfilter',
            index=models.Index(fields=['shared_by', 'created_at'], name='sharing_sha_shared__cc562a_idx'),
        ),
        migrations.AddIndex(
            model_name='sharedfilter',
            index=models.Index(fields=['intended_recipient_email'], name='sharing_sha_intende_3e48f1_idx'),
        ),
        migrations.AddIndex(
            model_name='sharedfilter',
            index=models.Index(fields=['intended_recipient_email', 'is_active'], name='sharing_sha_intende_b298fe_idx'),
        ),
    ]
