# Generated by Django 5.0 on 2025-08-14 07:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0007_add_shared_filter_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedfilter',
            name='shared_fields',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, help_text="Specific field slugs to include in this share (subset of filter's visible fields)", size=None),
        ),
    ]
