# Generated by Django 5.0 on 2025-08-14 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0008_add_shared_fields_to_sharedfilter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedfilter',
            name='access_mode',
            field=models.CharField(choices=[('view_only', 'View Only'), ('filtered_edit', 'Filtered Edit'), ('comment', 'View + Comment'), ('export', 'View + Export')], default='view_only', max_length=20),
        ),
    ]
