# Generated by Django 5.0 on 2025-08-05 22:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pipelines', '0005_update_access_level_default'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('record', 'Pipeline Record'), ('field', 'Pipeline Field'), ('document', 'Document'), ('user', 'User Profile')], max_length=50)),
                ('content_id', models.CharField(max_length=100)),
                ('content_hash', models.CharField(max_length=64)),
                ('embedding', models.JSONField()),
                ('model_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'indexes': [models.Index(fields=['content_type', 'content_id'], name='ai_aiembedd_content_976217_idx'), models.Index(fields=['content_hash'], name='ai_aiembedd_content_f6249c_idx'), models.Index(fields=['model_name'], name='ai_aiembedd_model_n_63c0ae_idx')],
                'unique_together': {('content_type', 'content_id', 'model_name')},
            },
        ),
        migrations.CreateModel(
            name='AIPromptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('prompt_template', models.TextField()),
                ('system_message', models.TextField(blank=True)),
                ('ai_provider', models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('local', 'Local')], max_length=20)),
                ('model_name', models.CharField(max_length=100)),
                ('temperature', models.DecimalField(decimal_places=2, default=0.7, max_digits=3)),
                ('max_tokens', models.IntegerField(default=1000)),
                ('field_types', models.JSONField(default=list)),
                ('pipeline_types', models.JSONField(default=list)),
                ('required_variables', models.JSONField(default=list)),
                ('optional_variables', models.JSONField(default=list)),
                ('version', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('is_system', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AIJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(choices=[('field_generation', 'Field Generation'), ('summarization', 'Summarization'), ('classification', 'Classification'), ('sentiment_analysis', 'Sentiment Analysis'), ('embedding_generation', 'Embedding Generation'), ('semantic_search', 'Semantic Search')], max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('record_id', models.IntegerField(blank=True, null=True)),
                ('field_name', models.CharField(blank=True, max_length=100)),
                ('ai_provider', models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('local', 'Local')], max_length=20)),
                ('model_name', models.CharField(max_length=100)),
                ('prompt_template', models.TextField(blank=True)),
                ('ai_config', models.JSONField(default=dict)),
                ('input_data', models.JSONField(default=dict)),
                ('output_data', models.JSONField(default=dict)),
                ('tokens_used', models.IntegerField(default=0)),
                ('cost_cents', models.IntegerField(default=0)),
                ('processing_time_ms', models.IntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('max_retries', models.IntegerField(default=3)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pipeline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pipelines.pipeline')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='ai_aijob_status_e4628c_idx'), models.Index(fields=['job_type'], name='ai_aijob_job_typ_df7927_idx'), models.Index(fields=['record_id'], name='ai_aijob_record__d025d5_idx'), models.Index(fields=['created_at'], name='ai_aijob_created_9747b2_idx')],
            },
        ),
        migrations.CreateModel(
            name='AIUsageAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_provider', models.CharField(max_length=20)),
                ('model_name', models.CharField(max_length=100)),
                ('operation_type', models.CharField(max_length=50)),
                ('tokens_used', models.IntegerField()),
                ('cost_cents', models.IntegerField()),
                ('response_time_ms', models.IntegerField(blank=True, null=True)),
                ('record_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('pipeline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pipelines.pipeline')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['date'], name='ai_aiusagea_date_75ce54_idx'), models.Index(fields=['user', 'date'], name='ai_aiusagea_user_id_4dc076_idx'), models.Index(fields=['ai_provider', 'date'], name='ai_aiusagea_ai_prov_e0ff39_idx'), models.Index(fields=['operation_type', 'date'], name='ai_aiusagea_operati_382a35_idx')],
            },
        ),
    ]
