# Generated by Django 5.0 on 2025-08-01 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formtemplate',
            name='allowed_user_types',
        ),
        migrations.RemoveField(
            model_name='formtemplate',
            name='duplicate_action',
        ),
        migrations.RemoveField(
            model_name='formtemplate',
            name='enable_duplicate_detection',
        ),
        migrations.RemoveField(
            model_name='formtemplate',
            name='is_public',
        ),
        migrations.RemoveField(
            model_name='formtemplate',
            name='public_slug',
        ),
        migrations.RemoveField(
            model_name='formtemplate',
            name='redirect_url',
        ),
        migrations.RemoveField(
            model_name='formtemplate',
            name='success_message',
        ),
        migrations.RemoveField(
            model_name='formtemplate',
            name='validation_mode',
        ),
        migrations.RemoveField(
            model_name='validationrule',
            name='is_async',
        ),
        migrations.AddField(
            model_name='formtemplate',
            name='dynamic_mode',
            field=models.CharField(blank=True, choices=[('all', 'All Fields'), ('stage', 'Stage-Specific Fields'), ('visible', 'Visible Fields Only')], help_text='For dynamic forms, which generation mode to use', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='formtemplate',
            name='form_type',
            field=models.CharField(choices=[('dynamic', 'Dynamic Form'), ('custom', 'Custom Form')], default='full', max_length=50),
        ),
        migrations.AlterField(
            model_name='formtemplate',
            name='target_stage',
            field=models.CharField(blank=True, help_text='For stage-specific dynamic forms, which stage to target', max_length=100),
        ),
        migrations.AlterField(
            model_name='validationrule',
            name='rule_type',
            field=models.CharField(choices=[('required', 'Required Field'), ('min_length', 'Minimum Length'), ('max_length', 'Maximum Length'), ('min_value', 'Minimum Value'), ('max_value', 'Maximum Value'), ('regex', 'Regular Expression'), ('email', 'Email Format'), ('phone', 'Phone Format')], max_length=50),
        ),
    ]
