# Generated by Django 5.0 on 2025-08-01 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_simplify_forms_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='formtemplate',
            name='success_message',
            field=models.TextField(blank=True, help_text='Message to show after successful form submission'),
        ),
    ]
